//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilverLeaf.Screener.Admin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilverLeaf.Screener.Admin.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas for improvement.
        /// </summary>
        internal static string AreasForImprovement {
            get {
                return ResourceManager.GetString("AreasForImprovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas of strength.
        /// </summary>
        internal static string AreasOfStrength {
            get {
                return ResourceManager.GetString("AreasOfStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assessor.
        /// </summary>
        internal static string Assessor {
            get {
                return ResourceManager.GetString("Assessor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot complete anymore.
        /// </summary>
        internal static string CannotComplete {
            get {
                return ResourceManager.GetString("CannotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Screener.
        /// </summary>
        internal static string CompleteScreener {
            get {
                return ResourceManager.GetString("CompleteScreener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehension.
        /// </summary>
        internal static string Comprehension {
            get {
                return ResourceManager.GetString("Comprehension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations!.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Screener.
        /// </summary>
        internal static string ContinueScreener {
            get {
                return ResourceManager.GetString("ContinueScreener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Recommendation.
        /// </summary>
        internal static string CourseRecommendation {
            get {
                return ResourceManager.GetString("CourseRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Student.
        /// </summary>
        internal static string CurrentStudent {
            get {
                return ResourceManager.GetString("CurrentStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download complete.
        /// </summary>
        internal static string DownloadComplete {
            get {
                return ResourceManager.GetString("DownloadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading file....
        /// </summary>
        internal static string DownloadingFile {
            get {
                return ResourceManager.GetString("DownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download screener.
        /// </summary>
        internal static string DownloadScreenerReport {
            get {
                return ResourceManager.GetString("DownloadScreenerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        internal static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra information gained.
        /// </summary>
        internal static string ExtraInformationGained {
            get {
                return ResourceManager.GetString("ExtraInformationGained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We need a few more details.
        /// </summary>
        internal static string FewMoreDetails {
            get {
                return ResourceManager.GetString("FewMoreDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished the comprehension section of the screener process.
        /// </summary>
        internal static string FinishedComprehensionMessage {
            get {
                return ResourceManager.GetString("FinishedComprehensionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished the introductory oral section of the screener progress.
        /// </summary>
        internal static string FinishedOralMessage {
            get {
                return ResourceManager.GetString("FinishedOralMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have finished the longest and most difficult section of the screener process, phonics.
        /// </summary>
        internal static string FinishedPhonicsMessage {
            get {
                return ResourceManager.GetString("FinishedPhonicsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Course Suggestion.
        /// </summary>
        internal static string GetCourseSuggestion {
            get {
                return ResourceManager.GetString("GetCourseSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap the Hamburger to get started.
        /// </summary>
        internal static string GettingStartedMessage {
            get {
                return ResourceManager.GetString("GettingStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade.
        /// </summary>
        internal static string Grade {
            get {
                return ResourceManager.GetString("Grade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string Issue {
            get {
                return ResourceManager.GetString("Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Screeners.
        /// </summary>
        internal static string MenuItemCompletedScreener {
            get {
                return ResourceManager.GetString("MenuItemCompletedScreener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string MenuItemLogin {
            get {
                return ResourceManager.GetString("MenuItemLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string MenuItemLogout {
            get {
                return ResourceManager.GetString("MenuItemLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Screeners.
        /// </summary>
        internal static string MenuItemPendingScreeners {
            get {
                return ResourceManager.GetString("MenuItemPendingScreeners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Screener.
        /// </summary>
        internal static string MenuItemResumeScreener {
            get {
                return ResourceManager.GetString("MenuItemResumeScreener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new Student.
        /// </summary>
        internal static string MenuItemScreenerRegistration {
            get {
                return ResourceManager.GetString("MenuItemScreenerRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device is currently unable to access the internet; Please try again later.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the save button below or tap the &apos;retry&apos; button from the top right to start again!.
        /// </summary>
        internal static string NextSteps {
            get {
                return ResourceManager.GetString("NextSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No completed screeners.
        /// </summary>
        internal static string NoCompletedScreenersMessage {
            get {
                return ResourceManager.GetString("NoCompletedScreenersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pending screeners.
        /// </summary>
        internal static string NoPendingStudentScreenersMessage {
            get {
                return ResourceManager.GetString("NoPendingStudentScreenersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oral.
        /// </summary>
        internal static string Oral {
            get {
                return ResourceManager.GetString("Oral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Screeners.
        /// </summary>
        internal static string PageTitleCompletedScreeners {
            get {
                return ResourceManager.GetString("PageTitleCompletedScreeners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Screener.
        /// </summary>
        internal static string PageTitleCompleteScreener {
            get {
                return ResourceManager.GetString("PageTitleCompleteScreener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehension.
        /// </summary>
        internal static string PageTitleComprehension {
            get {
                return ResourceManager.GetString("PageTitleComprehension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functional Oral.
        /// </summary>
        internal static string PageTitleFunctionalOral {
            get {
                return ResourceManager.GetString("PageTitleFunctionalOral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string PageTitleLogin {
            get {
                return ResourceManager.GetString("PageTitleLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Screeners.
        /// </summary>
        internal static string PageTitlePendingScreeners {
            get {
                return ResourceManager.GetString("PageTitlePendingScreeners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonics.
        /// </summary>
        internal static string PageTitlePhonics {
            get {
                return ResourceManager.GetString("PageTitlePhonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screener view.
        /// </summary>
        internal static string PageTitleScreenerPage {
            get {
                return ResourceManager.GetString("PageTitleScreenerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Student Information.
        /// </summary>
        internal static string PageTitleScreenerRegistration {
            get {
                return ResourceManager.GetString("PageTitleScreenerRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phonics.
        /// </summary>
        internal static string Phonics {
            get {
                return ResourceManager.GetString("Phonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume comprehension.
        /// </summary>
        internal static string ResumeComprehension {
            get {
                return ResourceManager.GetString("ResumeComprehension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume oral.
        /// </summary>
        internal static string ResumeOral {
            get {
                return ResourceManager.GetString("ResumeOral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume phonics.
        /// </summary>
        internal static string ResumePhonics {
            get {
                return ResourceManager.GetString("ResumePhonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screener page.
        /// </summary>
        internal static string ScreenerPage {
            get {
                return ResourceManager.GetString("ScreenerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a student above to get started.
        /// </summary>
        internal static string SelectStudentLabel {
            get {
                return ResourceManager.GetString("SelectStudentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        internal static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Info.
        /// </summary>
        internal static string StudentInfo {
            get {
                return ResourceManager.GetString("StudentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe left.
        /// </summary>
        internal static string SwipeLeft {
            get {
                return ResourceManager.GetString("SwipeLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swipe right.
        /// </summary>
        internal static string SwipeRight {
            get {
                return ResourceManager.GetString("SwipeRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an incorrect Username or Password.
        /// </summary>
        internal static string UsernamePasswordError {
            get {
                return ResourceManager.GetString("UsernamePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
